"""initial data

Revision ID: 92fe5eac1e02
Revises: 771c1829df84
Create Date: 2025-08-18 00:17:25.444101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fe5eac1e02'
down_revision = '771c1829df84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
