"""delete column in user

Revision ID: 9481f04b25fb
Revises: 8809cb676c50
Create Date: 2025-08-16 21:33:28.220074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9481f04b25fb'
down_revision = '8809cb676c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
